#!/usr/bin/env bash
# Set IFS to colon to split fields in /etc/passwd
IFS=':'
while read -r USERNAME PASSWORD USER_ID GROUP_ID TAM_AD HOME_DIRECTORY SHELL ; do
    echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $SHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $TAM_AD"
done < /etc/passwd
